name: Build

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8 for Build
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build
        run: |
          mvn -B clean verify
