name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: >
            [
              {
                "id": "central",
                "name": "paion-data-libs-release",
                "url": "https://paiondata.jfrog.io/artifactory/paion-data-libs-release",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "snapshots",
                "name": "paion-data-libs-snapshot",
                "url": "https://paiondata.jfrog.io/artifactory/paion-data-libs-snapshot",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "central",
                "name": "paion-data-libs-release",
                "url": "https://paiondata.jfrog.io/artifactory/paion-data-libs-release",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "snapshots",
                "name": "paion-data-libs-snapshot",
                "url": "https://paiondata.jfrog.io/artifactory/paion-data-libs-snapshot",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: >
            [
              {
                "id": "central",
                "username": "jack20220723@gmail.com",
                "password": "${{ secrets.ARTIFACTORY_CENTRAL_SERVER }}"
              },
              {
                "id": "snapshots",
                "username": "jack20220723@gmail.com",
                "password": "${{ secrets.ARTIFACTORY_SNAPSHOTS_SERVER }}"
              }
            ]
      - name: Publish Package to JFrog Artifactory
        run: mvn --batch-mode deploy
