name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Generate settings.xml for pushing Athena to Nexus 3
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{"id": "nexus", "username": "pd-headless-user", "password": "${{ secrets.NEXUS_HEADLESS_USER_TOKEN }}"}]'
      - name: Publish Package to GitHub Packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TO_ARTIFACTORY }}
